/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "charmREST",
            "endpoint": "https://war6a39h5e.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://cdkd2vmwbvdyhkxdlzzxrvarca.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4etx4js3x5gxdmhmjsev42otiy",
    "aws_cognito_identity_pool_id": "us-west-1:2fb4ec97-8fb6-4afa-b55a-91bf3d1a9d82",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_7eZ7pHAnC",
    "aws_user_pools_web_client_id": "7204bn9cch23u08b1dqdo72p1l",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "GENDER",
        "GIVEN_NAME",
        "UPDATED_AT"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "amplify-doctor",
            "region": "us-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "charmwebsite-storage-2ab2dd37233013-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
